### ISSUE TITLE
constructor(nav: NavController) throws a SyntaxError

### ISSUE THREAD

**Issue by thomascys** [TUIHackfridays/ionic-broodjesapp#1]
I tried to get the modals to work but as soon as i try to inject the NavController into the Constructor i always get a Syntax error which is strange cause i just copied the code from the v2 documentation.

```
./app/pages/page1/page1.js
Module build failed: SyntaxError: /Applications/MAMP/htdocs/ionic-broodjesapp/app/pages/page1/page1.js: Unexpected token (12:16)
  10 | 
  11 | export class Page1 {
> 12 |  constructor(nav: NavController) {
     |                 ^
```

I checked the [ionic-preview-app](https://github.com/driftyco/ionic-preview-app) that contains the same syntax but doesn't throw any errors when you run 'ionic serve'

Am i missing something crucial here?

**Comment by koenbetsens** [comment]
You might be required to import NavController

**Comment by iverdo01** [comment]
This (nav: NavController) syntax is for TypeScript only.
Too bad our project wasn't generated for TypeScript, but EcmaScript.

You should use the static function instead: 
`static get parameters() {
  return [[NavController]]
}
constructor(nav) {
  ...
}`

I already changed page1 functionality, so you would want to checkout my changed first.

**Comment by koenbetsens** [comment]
Thanks for the changes!
Typescript has it's own quirks and limitations - since the documentation on the new ionic beta is not complete yet, we might run in more problems.

That being said, feel free to consider yourself challenged and create a typescript-based branch so we can compare.

**Comment by wdedulle** [comment]
challenge accepted, new branch created
